In [4]:
import pandas as pd
import glob
import os

files = glob.glob("Data/quotazioni_omi_locazione_*.csv")

for f in files:
    anno_semestre = os.path.basename(f).replace('quotazioni_omi_locazione_', '').replace('.csv', '')
    nome_variabile = f"df_{anno_semestre}"    
    globals()[nome_variabile] = pd.read_csv(f, sep=';', encoding='latin1', decimal=',')


# I DF SI CHIAMANO df_ANNO_SEMESTRE.csv

In [21]:
# Esempio: guardiamo le prime righe del secondo semestre 2024
df_2023_1.head()

,Quotazioni Immobiliari : Valori di Mercato - Semestre 2023/1 - elaborazione del 21-NOV-23,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Area_territoriale,Regione,Prov,Comune_ISTAT,Comune_cat,Sez,Comune_amm,Comune_descrizione,Fascia,Zona,LinkZona,Cod_Tip,Descr_Tipologia,Stato,Stato_prev,Loc_min,Loc_max,Sup_NL_loc
1,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,20,Abitazioni civili,OTTIMO,,"29,8",40,L
2,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,20,Abitazioni civili,NORMALE,P,24,"29,7",L
3,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,21,Abitazioni di tipo economico,NORMALE,P,"19,5","24,5",L
4,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,21,Abitazioni di tipo economico,OTTIMO,,"24,6","29,5",L

In [8]:
df_2018_1.head()

,Area_territoriale,Regione,Prov,Comune_ISTAT,Comune_cat,Sez,Comune_amm,Comune_descrizione,Fascia,Zona,LinkZona,Cod_Tip,Descr_Tipologia,Stato,Stato_prev,Loc_min,Loc_max,Sup_NL_loc
0,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,20,Abitazioni civili,OTTIMO,,30.4,36.5,L
1,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,20,Abitazioni civili,NORMALE,P,23.8,30.0,L
2,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,21,Abitazioni di tipo economico,OTTIMO,,24.5,30.5,L
3,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,21,Abitazioni di tipo economico,NORMALE,P,18.5,22.5,L
4,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,19,Abitazioni signorili,OTTIMO,P,39.8,46.2,L

In [22]:


import pandas as pd
import glob

files = glob.glob("Data/quotazioni_omi_locazione_*.csv")

# 1. Prendiamo le colonne del primissimo file come "modello" di riferimento
colonne_base = set(pd.read_csv(files[0], sep=';', encoding='latin1', nrows=0).columns)

tutto_ok = True

# 2. Controlliamo tutti gli altri file
for f in files:
    colonne_attuali = set(pd.read_csv(f, sep=';', encoding='latin1', nrows=0).columns)
    
    if colonne_attuali != colonne_base:
        print(f"⚠️ Attenzione, colonne diverse nel file: {f}")
        tutto_ok = False

# 3. Risultato finale
if tutto_ok:
    print("✅ Controllo superato! Tutti i file hanno le stesse identiche colonne.")

⚠️ Attenzione, colonne diverse nel file: Data\quotazioni_omi_locazione_2023_1.csv

In [23]:
import pandas as pd

# Usiamo header=1 per saltare la prima riga "sporca" e prendere i nomi dalla seconda
df_2023_test = pd.read_csv("Data/quotazioni_omi_locazione_2023_1.csv", 
                           sep=';', 
                           encoding='latin1', 
                           header=1)

# Vediamo se ora i nomi delle colonne sono corretti
print("Colonne 2023 corrette:")
print(df_2023_test.columns)

Colonne 2023 corrette:
Index(['Area_territoriale', 'Regione', 'Prov', 'Comune_ISTAT', 'Comune_cat',
       'Sez', 'Comune_amm', 'Comune_descrizione', 'Fascia', 'Zona', 'LinkZona',
       'Cod_Tip', 'Descr_Tipologia', 'Stato', 'Stato_prev', 'Loc_min',
       'Loc_max', 'Sup_NL_loc'],
      dtype='str')

In [ ]:
# Sovrascriviamo la variabile sbagliata leggendo il file nel modo corretto
df_2023_1 = pd.read_csv("Data/quotazioni_omi_locazione_2023_1.csv", sep=';', encoding='latin1', header=1)

df_2023_1.head()

,Area_territoriale,Regione,Prov,Comune_ISTAT,Comune_cat,Sez,Comune_amm,Comune_descrizione,Fascia,Zona,LinkZona,Cod_Tip,Descr_Tipologia,Stato,Stato_prev,Loc_min,Loc_max,Sup_NL_loc
0,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,20,Abitazioni civili,OTTIMO,,"29,8",40,L
1,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,20,Abitazioni civili,NORMALE,P,24,"29,7",L
2,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,21,Abitazioni di tipo economico,NORMALE,P,"19,5","24,5",L
3,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,21,Abitazioni di tipo economico,OTTIMO,,"24,6","29,5",L
4,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,19,Abitazioni signorili,OTTIMO,P,33,47,L

In [28]:
df_2018_2.head()

,Area_territoriale,Regione,Prov,Comune_ISTAT,Comune_cat,Sez,Comune_amm,Comune_descrizione,Fascia,Zona,LinkZona,Cod_Tip,Descr_Tipologia,Stato,Stato_prev,Loc_min,Loc_max,Sup_NL_loc
0,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,20,Abitazioni civili,OTTIMO,,30.4,36.5,L
1,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,20,Abitazioni civili,NORMALE,P,23.5,30.4,L
2,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,21,Abitazioni di tipo economico,OTTIMO,,24.5,30.5,L
3,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,21,Abitazioni di tipo economico,NORMALE,P,18.5,22.5,L
4,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,19,Abitazioni signorili,OTTIMO,P,39.5,46.5,L

In [32]:
import pandas as pd

# 1. Gather all dataframes, add Year/Semester, and put them in a list
dfs_to_merge = [
    globals()[name].assign(Year=name.split('_')[1], Semester=name.split('_')[2])
    for name in list(globals().keys()) if name.startswith('df_20') and len(name) == 9
]

df_total = pd.concat(dfs_to_merge, ignore_index=True)

print(len(df_total))
display(df_total.head(10))

6729

,Area_territoriale,Regione,Prov,Comune_ISTAT,Comune_cat,Sez,Comune_amm,Comune_descrizione,Fascia,Zona,LinkZona,Cod_Tip,Descr_Tipologia,Stato,Stato_prev,Loc_min,Loc_max,Sup_NL_loc,Year,Semester
0,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,20,Abitazioni civili,OTTIMO,,30.4,36.5,L,2018,1
1,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,20,Abitazioni civili,NORMALE,P,23.8,30.0,L,2018,1
2,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,21,Abitazioni di tipo economico,OTTIMO,,24.5,30.5,L,2018,1
3,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,21,Abitazioni di tipo economico,NORMALE,P,18.5,22.5,L,2018,1
4,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,19,Abitazioni signorili,OTTIMO,P,39.8,46.2,L,2018,1
5,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,13,Box,NORMALE,P,14.0,20.0,L,2018,1
6,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,9,Magazzini,NORMALE,P,14.0,18.0,L,2018,1
7,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,5,Negozi,NORMALE,P,41.5,56.5,L,2018,1
8,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,5,Negozi,OTTIMO,,80.0,119.0,L,2018,1
9,NORD-OVEST,LOMBARDIA,MI,3015146,C1AA,,F205,MILANO,B,B12,MI00003228,6,Uffici,OTTIMO,P,24.0,34.5,L,2018,1

In [33]:
# Save the merged dataframe to the Data folder
df_total.to_csv('Data/total_rentals.csv', index=False, sep=';', encoding='latin1')

print("File 'total_rentals.csv' saved successfully in the Data folder!")

File 'total_rentals.csv' saved successfully in the Data folder!